# SPDX-License-Identifier: Apache-2.0
# Vite+ (vp) sits on top of pnpm workspaces. The `catalog:` entries pin the
# Vite+ toolchain packages; `packages` lists the workspace members.
#
# `apps/web` contains the repository's Node.js application.
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
packages:
  - apps/*
allowBuilds:
  canvas: set this to true or false
  esbuild: true
  msgpackr-extract: set this to true or false
  vue-demi: true
