# SPDX-License-Identifier: Apache-2.0
# Vite+ owns repository-level tooling. The Lingguang app intentionally remains
# outside this pnpm workspace: its official package-lock.json and npm toolchain
# are part of the platform build contract.
catalog:
  vite-plus: latest
allowBuilds:
  canvas: false
  esbuild: true
  vue-demi: true
