// SPDX-License-Identifier: Apache-2.0

//! 404-snf CA35 application.
//!
//! Orchestrates the full upper layer:
//!
//! 1. reads IWR6843 frames via [`snf_radar`] over the sensor's USB virtual COM
//!    port — the radar is a Linux tty, so this is a plain `tokio-serial` read,
//! 2. extracts indicators and classifies fatigue via [`snf_fatigue`] (ONNX),
//! 3. drives the pneumatics directly — pump on `TIM4_CH2`, vent valve on
//!    `TIM5_CH1`, both through FR120N MOSFET modules (see [`pneumatics`] /
//!    [`fr120n`] / [`sysfs_pwm`]), and
//! 4. publishes vitals, fatigue and status over BLE via [`snf_ble`] (BlueZ).
//!
//! So the whole data path is on this core. TIM4/TIM5 are reachable only from the
//! AP, which is why the pneumatics are here; the CM33 holds no actuator line,
//! which means there is no independent interlock — see [`pneumatics`] for how
//! shutdown is made fail-safe instead.
//!
//! The CM33 still owns USART6 and still offers parsed frames over the `radar`
//! IPC channel (see `crates/mcu`), but that is **not** the default source: with
//! the sensor on virtual COM there is nothing on USART6 to read. This binary
//! only checks the link at start-up.
//!
//! Reading runs in its own task so a `tokio::select!` branch firing never cancels
//! a partial UART read.
//!
//! The UIO bring-up, IPC transceivers, and defmt console live in
//! `consortium.gen.rs`, generated by `csti build` from `../../Consortium.toml`
//! and `include!`d below. `#[consortium_runtime_app::main]` calls the generated
//! `init()` and hands the body a `Context` whose `ipc_shm.radar` field is a
//! ready `Transceiver<RadarControl, RadarReport>`.

#![cfg(target_os = "linux")]

use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use snf_ble::{
    BleTransport, Telemetry,
    protocol::{ProtocolInfo, capabilities, streams},
};
use snf_bridge::{Accounting, StreamState, map};
use snf_fatigue::FatigueModel;
use snf_radar::{IndicatorEngine, RadarConfig, RadarFrame, RadarStream};
use snf_shared::{RadarControl, RadarReport};

mod fr120n;
mod pneumatics;
mod sysfs_pwm;

use pneumatics::{PneumaticConfig, PneumaticState, Pneumatics};

/// Path to the ONNX fatigue model on the deployed image.
const MODEL_PATH: &str = "/opt/snf/fatigue.onnx";
/// Revision reported in the Fatigue payload's `model_revision`.
const MODEL_REVISION: u32 = 1;
/// Firmware build id for Protocol Info; `0` until wired to the build system.
const BUILD_ID: u32 = 0;
/// Fatigue level at or above which the pneumatics are asked to actuate.
const FATIGUE_ALERT_LEVEL: u8 = 70;
/// Device Status notify period (`PROTOCOL.md` §13 default: 1 Hz).
const STATUS_PERIOD: Duration = Duration::from_secs(1);
/// How often the pneumatic state is re-evaluated. Independent of the radar so
/// [`MAX_INFLATE`] still expires if frames stop mid-inflation.
const ACTUATOR_PERIOD: Duration = Duration::from_millis(100);
/// Streams this build can serve: no pose model yet, so `POSE_3D` stays clear.
const DEVICE_CAPABILITIES: u32 = capabilities::VITALS | capabilities::FATIGUE;
/// Upper bound on point-cloud points advertised in Protocol Info.
const MAX_POINTS: u8 = 96;
/// IWR6843 data port.
///
/// The sensor is wired over its USB virtual COM, so both of its UARTs enumerate
/// on Linux: the XDS110 on an ISK/BoosterPack presents the CLI port first and
/// the data port second (`/dev/ttyACM0` and `/dev/ttyACM1`). A bare FTDI cable
/// instead gives `/dev/ttyUSB0`/`/dev/ttyUSB1` — check `dmesg` after plugging in.
const RADAR_DATA_PORT: &str = "/dev/ttyACM1";

/// Pump duty while inflating, as a percentage.
const PUMP_DUTY_PERCENT: u8 = 70;
/// Hard ceiling on one uninterrupted inflation.
///
/// There is no pressure sensor in the loop yet and no independent interlock
/// behind it, so this bounds how much air a stuck alert — or a run killed
/// mid-inflation — can put into the bladder. After it elapses the pump stops and
/// the valve holds until the alert clears.
const MAX_INFLATE: Duration = Duration::from_secs(6);

/// A best-effort boot identifier that changes across restarts, so clients can
/// detect a reboot and flush per-sequence state (`PROTOCOL.md` §14).
fn boot_id() -> u32 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.subsec_nanos() ^ (d.as_secs() as u32))
        .unwrap_or(0)
}

/// Minimum spacing between Vitals notifications for a requested rate.
fn vitals_period(hz: u8) -> Duration {
    Duration::from_millis(1000 / hz.max(1) as u64)
}

/// A radar frame or a gap, forwarded from the reader task. Reading runs in its
/// own task so a `tokio::select!` branch firing never cancels a partial UART
/// read.
enum RadarEvent {
    Frame(RadarFrame),
    Gap,
}

/// What the pneumatics should be doing, given the current alert and how long it
/// has been asserted.
fn desired_state(alert_since: Option<Instant>, now: Instant) -> PneumaticState {
    match alert_since {
        None => PneumaticState::Vent,
        Some(since) if now.duration_since(since) < MAX_INFLATE => {
            PneumaticState::Inflate(PUMP_DUTY_PERCENT)
        }
        Some(_) => PneumaticState::Hold,
    }
}

// Generated by `csti build`; absent until the pipeline runs (see this crate's
// README). Not compiled by the workspace `cargo check`.
include!("consortium.gen.rs");

/// Reports a bring-up failure and exits. Hit when `init()` cannot open the UIO
/// devices or the descriptor handshake fails — most often a plain dev host with
/// no `/dev/uioN`.
#[consortium_runtime_app::fail]
fn on_init_failure(err: ConsortiumInitError) {
    tracing_subscriber::fmt::init();
    tracing::error!("snf-app: IPC bring-up failed: {err:?}");
}

#[consortium_runtime_app::main]
async fn main(mut context: Context) {
    tracing_subscriber::fmt::init();
    tracing::info!("snf-app: CA35 application started; IPC bring-up complete");

    // ── BLE peripheral: advertise and serve the SNF telemetry service ────────
    let info = ProtocolInfo {
        capabilities: DEVICE_CAPABILITIES,
        max_point_count: MAX_POINTS as u16,
        max_pose_joints: 0,
        max_subjects: 1,
        boot_id: boot_id(),
        build_id: BUILD_ID,
    };
    let mut ble = snf_ble::BluezPeripheral::new(None, info);
    if let Err(e) = ble.start().await {
        tracing::error!("snf-app: BLE start failed: {e}");
        return;
    }
    let mut control = ble
        .control_requests()
        .expect("control receiver is taken exactly once");
    let mut stream_state = StreamState::default();
    let mut accounting = Accounting::new(stream_state.stream_mask);

    // ── Pneumatics: pump on TIM4_CH2, vent valve on TIM5_CH1 ─────────────────
    // Optional: without the PWM chips (wrong device tree, wrong chip index) the
    // sensing half is still worth running, so this degrades to telemetry-only
    // rather than refusing to start.
    let mut pneumatics = match Pneumatics::open(PneumaticConfig::default()) {
        Ok(pneumatics) => Some(pneumatics),
        Err(e) => {
            tracing::warn!("snf-app: pneumatics unavailable ({e}); running without actuation");
            None
        }
    };

    // ── CM33 link check ──────────────────────────────────────────────────────
    // The CM33 owns USART6 and can serve parsed frames over this channel, but
    // with the sensor on virtual COM there is nothing on USART6 to read. Tell it
    // so once, and log the reply as proof the shared-memory link came up.
    check_cm33_link(&mut context).await;

    // ── Radar pipeline: read frames in a task, extract indicators here ───────
    let radar_config = RadarConfig {
        data_port: RADAR_DATA_PORT.to_string(),
        ..RadarConfig::default()
    };
    let radar = match RadarStream::open(radar_config) {
        Ok(radar) => radar,
        Err(e) => {
            tracing::error!("snf-app: radar open on {RADAR_DATA_PORT} failed: {e}");
            return;
        }
    };
    let (frame_tx, mut frame_rx) = tokio::sync::mpsc::channel::<RadarEvent>(4);
    tokio::spawn(read_radar(radar, frame_tx));
    let mut indicators = IndicatorEngine::default();

    // Fatigue is optional: without a model we still publish vitals and status.
    let fatigue_model = match FatigueModel::load(MODEL_PATH) {
        Ok(model) => Some(model),
        Err(e) => {
            tracing::warn!("snf-app: fatigue model unavailable ({e}); running without fatigue");
            None
        }
    };

    let mut status_tick = tokio::time::interval(STATUS_PERIOD);
    let mut actuator_tick = tokio::time::interval(ACTUATOR_PERIOD);
    let mut last_vitals_at: Option<Instant> = None;
    let mut alert_since: Option<Instant> = None;

    loop {
        tokio::select! {
            // Radar frame → indicators → Vitals (rate-limited) + Fatigue.
            Some(event) = frame_rx.recv() => {
                let RadarEvent::Frame(frame) = event else {
                    accounting.note_radar_gap();
                    continue;
                };
                let now = Instant::now();
                let snapshot = indicators.update(now, &frame);

                let vitals_due = last_vitals_at
                    .is_none_or(|last| now.duration_since(last) >= vitals_period(stream_state.vitals_hz));
                if !vitals_due {
                    continue;
                }
                last_vitals_at = Some(now);

                if stream_state.stream_mask & streams::VITALS != 0 {
                    let mapped = map::vitals(&snapshot);
                    if let Err(e) = ble.publish(Telemetry::Vitals(mapped.payload), mapped.header_flags).await {
                        tracing::warn!("snf-app: vitals publish failed: {e}");
                    }
                }

                // Fatigue drives both the BLE record and the pneumatics, so it
                // runs whether or not anyone is subscribed to that stream.
                if let Some(model) = &fatigue_model {
                    match model.infer(&map::fatigue_features(&snapshot)) {
                        Ok(verdict) => {
                            let alert = verdict.level >= FATIGUE_ALERT_LEVEL;
                            match (alert, alert_since) {
                                (true, None) => alert_since = Some(now),
                                (false, Some(_)) => alert_since = None,
                                _ => {}
                            }

                            if stream_state.stream_mask & streams::FATIGUE != 0 {
                                let payload = map::fatigue_telemetry(verdict, MODEL_REVISION);
                                if let Err(e) = ble.publish(Telemetry::Fatigue(payload), 0).await {
                                    tracing::warn!("snf-app: fatigue publish failed: {e}");
                                }
                            }
                        }
                        Err(e) => tracing::warn!("snf-app: inference failed: {e}"),
                    }
                }
            }

            // Stream Control request from a BLE client.
            Some(request) = control.recv() => {
                let response = stream_state.apply(&request, DEVICE_CAPABILITIES, MAX_POINTS);
                accounting.active_streams = stream_state.stream_mask;
                if let Err(e) = ble.respond(response).await {
                    tracing::warn!("snf-app: control response failed: {e}");
                }
            }

            // Device Status notify (1 Hz).
            _ = status_tick.tick() => {
                if stream_state.stream_mask & streams::STATUS != 0 {
                    if let Err(e) = ble.publish(Telemetry::Status(accounting.snapshot()), 0).await {
                        tracing::warn!("snf-app: status publish failed: {e}");
                    }
                }
            }

            // Apply the actuator state. On its own tick rather than inline with
            // the fatigue verdict, so `MAX_INFLATE` still expires when the radar
            // goes quiet mid-inflation.
            _ = actuator_tick.tick() => {
                let mut failed = false;
                if let Some(actuators) = pneumatics.as_mut() {
                    let desired = desired_state(alert_since, Instant::now());
                    if desired != actuators.state() {
                        match actuators.set_state(desired) {
                            Ok(()) => tracing::debug!("snf-app: pneumatics -> {desired:?}"),
                            Err(e) => {
                                tracing::error!("snf-app: pneumatics write failed: {e}; venting");
                                // A failed write leaves the pair in an unknown
                                // combination. Vent once, then give up actuating
                                // rather than keep poking a broken PWM chip.
                                let _ = actuators.set_state(PneumaticState::Vent);
                                failed = true;
                            }
                        }
                    }
                }
                if failed {
                    // Dropping vents again and unexports both channels, leaving
                    // the pins low; telemetry keeps running.
                    pneumatics = None;
                }
            }
        }
    }
}

/// Ping the CM33 once and log its reply, so a dead shared-memory link shows up at
/// start-up rather than the first time something needs it.
///
/// `streaming: false` parks the CM33's USART6 front-end: nothing is wired to that
/// port in the virtual-COM configuration, so there is no reason for it to spin.
async fn check_cm33_link(context: &mut Context) {
    let request = RadarControl {
        seq: 0,
        streaming: false,
    };
    if let Err(e) = context.ipc_shm.radar.send(&request).await {
        tracing::warn!("snf-app: CM33 link check send failed: {e}");
        return;
    }
    match context.ipc_shm.radar.recv().await {
        Ok(message) => {
            let report: RadarReport = message.into_inner();
            tracing::info!("snf-app: CM33 link up (report seq={})", report.seq);
        }
        Err(e) => tracing::warn!("snf-app: CM33 link check recv failed: {e}"),
    }
}

/// Read radar frames until the stream ends, forwarding each as a [`RadarEvent`].
/// Runs in its own task so `next_frame`'s UART read is never cancelled by the
/// main loop's `select!`.
async fn read_radar(mut radar: RadarStream, tx: tokio::sync::mpsc::Sender<RadarEvent>) {
    loop {
        match radar.next_frame().await {
            Ok(Some(frame)) => {
                if tx.send(RadarEvent::Frame(frame)).await.is_err() {
                    break; // main loop dropped the receiver
                }
            }
            Ok(None) => {
                tracing::warn!("snf-app: radar stream ended");
                break;
            }
            Err(e) => {
                tracing::warn!("snf-app: radar frame error: {e}");
                if tx.send(RadarEvent::Gap).await.is_err() {
                    break;
                }
            }
        }
    }
}
