// SPDX-License-Identifier: Apache-2.0

//! 404-snf CA35 application.
//!
//! Orchestrates the full upper layer:
//!
//! 1. reads IWR6843 frames via [`snf_radar`] (pure-Rust UART and TLV parsing),
//! 2. extracts features and classifies fatigue via [`snf_fatigue`] (ONNX),
//! 3. drives the pump locally (TB6612 + Linux sysfs PWM, see [`tb6612`] /
//!    [`sysfs_pwm`]) and heartbeats the CM33 safety supervisor with a
//!    [`PneumaticCommand`] over the generated `actuator` transceiver — the CM33
//!    independently cuts the pump power rail if this heartbeat stops — consuming
//!    the returned [`PneumaticStatus`] (interlock state), and
//! 4. publishes the fatigue verdict over BLE via [`snf_ble`] (BlueZ).
//!
//! The UIO bring-up, IPC transceivers, and defmt console live in
//! `consortium.gen.rs`, generated by `csti build` from `../../Consortium.toml`
//! and `include!`d below. `#[consortium_runtime_app::main]` calls the generated
//! `init()` and hands the body a `Context` whose `ipc_shm.actuator` field is a
//! ready `Transceiver<PneumaticCommand, PneumaticStatus>`.
//!
//! Scaffold: the body heartbeats the supervisor in a stub loop; radar/fatigue/BLE
//! and the local pump control loop are sketched but not driven yet.

#![cfg(target_os = "linux")]

use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use snf_ble::{
    BleTransport, Telemetry,
    protocol::{ProtocolInfo, capabilities, streams},
};
use snf_bridge::{Accounting, StreamState, map};
use snf_fatigue::FatigueModel;
use snf_radar::{IndicatorEngine, RadarConfig, RadarFrame, RadarStream};
use snf_shared::{PneumaticCommand, PneumaticStatus};

// Pneumatic pump actuation (TB6612FNG H-bridge + Linux sysfs PWM). The pump
// drive itself is not wired here yet — the CA35 currently gates the rail via the
// `pump_enable` heartbeat and the CM33 interlock; local PWM construction from a
// `CdevPin`/`SysfsPwm` set follows once the board pin map is fixed.
#[allow(dead_code)]
mod sysfs_pwm;
#[allow(dead_code)]
mod tb6612;

/// Path to the ONNX fatigue model on the deployed image.
const MODEL_PATH: &str = "/opt/snf/fatigue.onnx";
/// Revision reported in the Fatigue payload's `model_revision`.
const MODEL_REVISION: u32 = 1;
/// Firmware build id for Protocol Info; `0` until wired to the build system.
const BUILD_ID: u32 = 0;
/// Fatigue level at or above which the pneumatics are asked to actuate.
const FATIGUE_ALERT_LEVEL: u8 = 70;
/// CM33 safety heartbeat period (~10 Hz; the CM33 deadman is 500 ms).
const HEARTBEAT_PERIOD: Duration = Duration::from_millis(100);
/// Device Status notify period (`PROTOCOL.md` §13 default: 1 Hz).
const STATUS_PERIOD: Duration = Duration::from_secs(1);
/// Streams this build can serve: no pose model yet, so `POSE_3D` stays clear.
const DEVICE_CAPABILITIES: u32 = capabilities::VITALS | capabilities::FATIGUE;
/// Upper bound on point-cloud points advertised in Protocol Info.
const MAX_POINTS: u8 = 96;

/// A radar frame or a gap, forwarded from the reader task. Reading runs in its
/// own task so a `tokio::select!` branch firing never cancels a partial UART
/// read.
enum RadarEvent {
    Frame(RadarFrame),
    Gap,
}

/// A best-effort boot identifier that changes across restarts, so clients can
/// detect a reboot and flush per-sequence state (`PROTOCOL.md` §14).
fn boot_id() -> u32 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.subsec_nanos() ^ (d.as_secs() as u32))
        .unwrap_or(0)
}

/// Minimum spacing between Vitals notifications for a requested rate.
fn vitals_period(hz: u8) -> Duration {
    Duration::from_millis(1000 / hz.max(1) as u64)
}

// Generated by `csti build`; absent until the pipeline runs (see this crate's
// README). Not compiled by the workspace `cargo check`.
include!("consortium.gen.rs");

/// Reports a bring-up failure and exits. Hit when `init()` cannot open the UIO
/// devices or the descriptor handshake fails — most often a plain dev host with
/// no `/dev/uioN`.
#[consortium_runtime_app::fail]
fn on_init_failure(err: ConsortiumInitError) {
    tracing_subscriber::fmt::init();
    tracing::error!("snf-app: IPC bring-up failed: {err:?}");
}

#[consortium_runtime_app::main]
async fn main(mut context: Context) {
    tracing_subscriber::fmt::init();
    tracing::info!("snf-app: CA35 application started; IPC bring-up complete");

    // ── BLE peripheral: advertise and serve the SNF telemetry service ────────
    let info = ProtocolInfo {
        capabilities: DEVICE_CAPABILITIES,
        max_point_count: MAX_POINTS as u16,
        max_pose_joints: 0,
        max_subjects: 1,
        boot_id: boot_id(),
        build_id: BUILD_ID,
    };
    let mut ble = snf_ble::BluezPeripheral::new(None, info);
    if let Err(e) = ble.start().await {
        tracing::error!("snf-app: BLE start failed: {e}");
        return;
    }
    let mut control = ble
        .control_requests()
        .expect("control receiver is taken exactly once");
    let mut stream_state = StreamState::default();
    let mut accounting = Accounting::new(stream_state.stream_mask);

    // ── Radar pipeline: read frames in a task, extract indicators here ───────
    let radar = match RadarStream::open(RadarConfig::default()) {
        Ok(radar) => radar,
        Err(e) => {
            tracing::error!("snf-app: radar open failed: {e}");
            return;
        }
    };
    let (frame_tx, mut frame_rx) = tokio::sync::mpsc::channel::<RadarEvent>(4);
    tokio::spawn(read_radar(radar, frame_tx));
    let mut indicators = IndicatorEngine::default();

    // Fatigue is optional: without a model we still publish vitals and status.
    let fatigue_model = match FatigueModel::load(MODEL_PATH) {
        Ok(model) => Some(model),
        Err(e) => {
            tracing::warn!("snf-app: fatigue model unavailable ({e}); running without fatigue");
            None
        }
    };

    let mut heartbeat = tokio::time::interval(HEARTBEAT_PERIOD);
    let mut status_tick = tokio::time::interval(STATUS_PERIOD);
    let mut seq: u32 = 0;
    let mut last_vitals_at: Option<Instant> = None;
    let mut pump_enable = false;

    loop {
        tokio::select! {
            // Radar frame → indicators → Vitals (rate-limited) + Fatigue.
            Some(event) = frame_rx.recv() => {
                let RadarEvent::Frame(frame) = event else {
                    accounting.note_radar_gap();
                    continue;
                };
                let now = Instant::now();
                let snapshot = indicators.update(now, &frame);

                let vitals_due = last_vitals_at
                    .is_none_or(|last| now.duration_since(last) >= vitals_period(stream_state.vitals_hz));
                if stream_state.stream_mask & streams::VITALS != 0 && vitals_due {
                    last_vitals_at = Some(now);
                    let mapped = map::vitals(&snapshot);
                    if let Err(e) = ble.publish(Telemetry::Vitals(mapped.payload), mapped.header_flags).await {
                        tracing::warn!("snf-app: vitals publish failed: {e}");
                    }

                    if let Some(model) = &fatigue_model {
                        match model.infer(&map::fatigue_features(&snapshot)) {
                            Ok(verdict) => {
                                pump_enable = verdict.level >= FATIGUE_ALERT_LEVEL;
                                if stream_state.stream_mask & streams::FATIGUE != 0 {
                                    let payload = map::fatigue_telemetry(verdict, MODEL_REVISION);
                                    if let Err(e) = ble.publish(Telemetry::Fatigue(payload), 0).await {
                                        tracing::warn!("snf-app: fatigue publish failed: {e}");
                                    }
                                }
                            }
                            Err(e) => tracing::warn!("snf-app: inference failed: {e}"),
                        }
                    }
                }
            }

            // Stream Control request from a BLE client.
            Some(request) = control.recv() => {
                let response = stream_state.apply(&request, DEVICE_CAPABILITIES, MAX_POINTS);
                accounting.active_streams = stream_state.stream_mask;
                if let Err(e) = ble.respond(response).await {
                    tracing::warn!("snf-app: control response failed: {e}");
                }
            }

            // Device Status notify (1 Hz).
            _ = status_tick.tick() => {
                if stream_state.stream_mask & streams::STATUS != 0 {
                    if let Err(e) = ble.publish(Telemetry::Status(accounting.snapshot()), 0).await {
                        tracing::warn!("snf-app: status publish failed: {e}");
                    }
                }
            }

            // CM33 safety heartbeat over the actuator IPC channel. `pump_enable`
            // reflects the latest fatigue verdict; the CM33 independently cuts the
            // rail if this heartbeat stops.
            _ = heartbeat.tick() => {
                let command = PneumaticCommand { seq, pump_enable };
                if let Err(e) = context.ipc_shm.actuator.send(&command).await {
                    tracing::error!("snf-app: ipc send error: {e}");
                    break;
                }
                match context.ipc_shm.actuator.recv().await {
                    Ok(msg) => {
                        let status: PneumaticStatus = msg.into_inner();
                        if status.tripped {
                            tracing::warn!(
                                "snf-app: pneumatic interlock TRIPPED (rail_enabled={}, seq={})",
                                status.rail_enabled,
                                status.seq,
                            );
                        }
                    }
                    Err(e) => {
                        tracing::error!("snf-app: ipc recv error: {e}");
                        break;
                    }
                }
                seq = seq.wrapping_add(1);
            }
        }
    }
}

/// Read radar frames until the stream ends, forwarding each as a [`RadarEvent`].
/// Runs in its own task so `next_frame`'s UART read is never cancelled by the
/// main loop's `select!`.
async fn read_radar(mut radar: RadarStream, tx: tokio::sync::mpsc::Sender<RadarEvent>) {
    loop {
        match radar.next_frame().await {
            Ok(Some(frame)) => {
                if tx.send(RadarEvent::Frame(frame)).await.is_err() {
                    break; // main loop dropped the receiver
                }
            }
            Ok(None) => {
                tracing::warn!("snf-app: radar stream ended");
                break;
            }
            Err(e) => {
                tracing::warn!("snf-app: radar frame error: {e}");
                if tx.send(RadarEvent::Gap).await.is_err() {
                    break;
                }
            }
        }
    }
}
