// SPDX-License-Identifier: Apache-2.0

//! 404-snf CA35 application.
//!
//! Orchestrates the full upper layer:
//!
//! 1. reads IWR6843 frames via [`snf_radar`] (pure-Rust UART and TLV parsing),
//! 2. extracts features and classifies fatigue via [`snf_fatigue`] (ONNX),
//! 3. sends a [`PneumaticCommand`] to the CM33 over the generated `actuator`
//!    transceiver, and consumes the returned [`PneumaticStatus`],
//! 4. publishes the fatigue verdict over BLE via [`snf_ble`] (BlueZ).
//!
//! The UIO bring-up, IPC transceivers, and defmt console live in
//! `consortium.gen.rs`, generated by `csti build` from `../../Consortium.toml`
//! and `include!`d below. `#[consortium_runtime_app::main]` calls the generated
//! `init()` and hands the body a `Context` whose `ipc_shm.actuator` field is a
//! ready `Transceiver<PneumaticCommand, PneumaticStatus>`.
//!
//! Scaffold: the body is a stub receive loop; radar/fatigue/BLE wiring is
//! sketched but not driven yet.

#![cfg(target_os = "linux")]

use snf_shared::{PneumaticCommand, PneumaticStatus};

// Generated by `csti build`; absent until the pipeline runs (see this crate's
// README). Not compiled by the workspace `cargo check`.
include!("consortium.gen.rs");

/// Reports a bring-up failure and exits. Hit when `init()` cannot open the UIO
/// devices or the descriptor handshake fails — most often a plain dev host with
/// no `/dev/uioN`.
#[consortium_runtime_app::fail]
fn on_init_failure(err: ConsortiumInitError) {
    tracing_subscriber::fmt::init();
    tracing::error!("snf-app: IPC bring-up failed: {err:?}");
}

#[consortium_runtime_app::main]
async fn main(mut context: Context) {
    tracing_subscriber::fmt::init();
    tracing::info!("snf-app: CA35 application started; IPC bring-up complete");

    // Sketch of the intended wiring (kept inert for the scaffold):
    //
    //   let mut radar = snf_radar::RadarStream::open(Default::default())?;
    //   let model = snf_fatigue::FatigueModel::load("/opt/snf/fatigue.onnx")?;
    //   let mut ble = snf_ble::BluezPeripheral::new(None);
    //   ble.start().await?;
    //
    //   while let Some(frame) = radar.next_frame().await? {
    //       let features = extract_features(&frame);
    //       let verdict = model.infer(&features)?;
    //       let cmd = PneumaticCommand { .. verdict .. };
    //       context.ipc_shm.actuator.send(&cmd).await?;
    //       ble.publish(verdict.into()).await?;
    //   }

    let mut seq: u32 = 0;
    loop {
        match context.ipc_shm.actuator.recv().await {
            Ok(msg) => {
                let status: PneumaticStatus = msg.into_inner();
                tracing::debug!(
                    "snf-app: pneumatic status pressure_kpa={} pump_on={} seq={}",
                    status.pressure_kpa,
                    status.pump_on,
                    status.seq,
                );

                // Placeholder command derived from a (not-yet-computed) verdict.
                let command = PneumaticCommand {
                    target_pressure_kpa: 0,
                    actuator_mask: 0,
                    mode: 0,
                };
                let _ = context.ipc_shm.actuator.send(&command).await;
                seq = seq.wrapping_add(1);
            }
            Err(e) => {
                eprintln!("snf-app: ipc recv error: {e}");
                break;
            }
        }
    }

    let _ = seq;
}
