// SPDX-License-Identifier: Apache-2.0

//! 404-snf CM33 firmware: the pneumatic actuation controller.
//!
//! Receives [`PneumaticCommand`] from the CA35 over the generated `actuator`
//! transceiver, drives the pump (PWM via TIM3 → DRV8871) and the solenoid valves
//! (GPIO → TPL7407L), reads bladder pressure (I2C → Honeywell MPRLS), and reports
//! [`PneumaticStatus`] back. See `hardware/pneumatics/README.md` for the BOM.
//!
//! All shared-memory / doorbell / MPU / NVIC / time-driver wiring lives in
//! `consortium.gen.rs`, generated by `csti build` from `../../Consortium.toml`
//! and `include!`d below. `#[consortium_runtime_mcu::main]` calls the generated
//! `init()` and hands the body a `Context` whose `ipc_shm.actuator` field is a
//! `Transceiver<PneumaticStatus, PneumaticCommand>`.
//!
//! Scaffold: the control loop echoes a stub status; no peripheral is driven yet.

#![no_std]
#![no_main]

use consortium_hal_stm32mp2::interrupt;
use embassy_executor::Spawner;
use embassy_time::Timer;
use snf_shared::{PneumaticCommand, PneumaticStatus};

// Generated by `csti build`; absent until the pipeline runs (see this crate's
// README). Depending on `consortium-dbg` with `logger` registers the defmt sink.
include!("consortium.gen.rs");

#[consortium_runtime_mcu::main]
async fn main(context: Context, _spawner: Spawner) {
    let mut actuator = context.ipc_shm.actuator;

    let mut seq: u32 = 0;
    loop {
        // Real loop: apply the latest command to pump/valves, then sample the
        // pressure sensor for closed-loop control. Stubbed here.
        if let Ok(msg) = actuator.recv().await {
            let cmd: PneumaticCommand = msg.into_inner();
            defmt::info!(
                "actuator cmd target_kpa={=u16} mask={=u8} mode={=u8}",
                cmd.target_pressure_kpa,
                cmd.actuator_mask,
                cmd.mode,
            );
        }

        let status = PneumaticStatus {
            pressure_kpa: 0,
            pump_on: false,
            seq,
        };
        let _ = actuator.send(&status).await;
        seq = seq.wrapping_add(1);

        Timer::after_millis(50).await;
    }
}

// IPCC RX-occupied vectors: the application owns these and forwards each to the
// shared IPCC waker so waiting `IpccDoorbell::wait` futures make progress.
#[interrupt]
fn IPCC1_RX() {
    consortium_runtime_mcu::log::trace!("ipcc1_rx interrupt: doorbell RX occupied");
    // SAFETY: this is the validated IPCC1 base used by the generated
    // Secondary-side doorbell.
    unsafe {
        consortium_ipc_doorbell_ipcc::notify_rx_occupied_interrupt::<consortium_ipc::Secondary, 1>(
            0x4049_0000,
        );
    }
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    cortex_m::interrupt::disable();
    loop {
        core::sync::atomic::compiler_fence(core::sync::atomic::Ordering::SeqCst);
        cortex_m::asm::wfi();
    }
}
