// SPDX-License-Identifier: Apache-2.0

//! 404-snf CM33 firmware: the IWR6843 radar front-end.
//!
//! The board's RIF configuration reaches USART6 only from the CM33, and reaches
//! TIM4/TIM5 — the two PWM-capable timers on the 40-pin connector — only from
//! the CA35. So the pneumatics live entirely on Linux and this core holds no
//! actuator line at all: it owns the radar data UART, and that is its whole job.
//!
//! It does the parsing too. Bytes off USART6 go through [`PacketAssembler`] to
//! recover whole packets, then [`parse_report`] reduces each packet's TLVs to a
//! fixed-size [`RadarReport`]: up to 32 detections in millimetres plus the
//! frame's aggregates. Raw point clouds never cross the IPC boundary — a frame is
//! ~2 KB of `f32`, the report is ~400 B of integers the CA35 can use directly.
//!
//! The transfer is a strict **pull**: the CA35 sends a [`RadarControl`] and this
//! core answers with the newest report, or one marked `fresh = false` when
//! nothing new has arrived. That needs no `select!` over the single-slot channel,
//! and backpressure lands in the interrupt-filled UART ring — which is exactly
//! what it is for — rather than in a queue nobody drains.
//!
//! Shared-memory / doorbell / MPU / NVIC / time-driver bring-up lives in
//! `consortium.gen.rs`, generated by `csti build` from `../../Consortium.toml`
//! and `include!`d below. `#[consortium_runtime_mcu::main]` calls the generated
//! `init()` and hands the body a `Context` whose `ipc_shm.radar` field is a
//! `Transceiver<RadarReport, RadarControl>`.
//!
//! The USART itself is **not** generated: `csti` emits bring-up for I2C and GPIO
//! blocks only, so the `[peripheral.usart6]` entry in `Consortium.toml` is
//! declarative and the driver below is constructed by hand from the chip map's
//! base and interrupt number — the same way the `IPCC1_RX` vector already
//! hardcodes the validated IPCC1 base.

#![no_std]
#![no_main]

use consortium_hal_stm32mp2::Interrupt;
use consortium_hal_stm32mp2::interrupt;
use consortium_hal_stm32mp2::uart::{BufferedUart, BufferedUartState, Config};
use embassy_executor::Spawner;
use embassy_time::{Duration, with_timeout};
use snf_shared::detect::{PacketAssembler, parse_report};
use snf_shared::{RadarControl, RadarReport};

// Generated by `csti build`; absent until the pipeline runs (see this crate's
// README). Depending on `consortium-dbg` with `logger` registers the defmt sink.
include!("consortium.gen.rs");

/// USART6 register base as the CM33 sees it, from the stm32mp25 chip map
/// (non-secure alias; `[peripheral.usart6] secure = false`).
const USART6_BASE: *mut () = 0x4022_0000 as *mut ();

/// USART6 kernel clock, in Hz.
///
/// **Confirm against your RCC setup.** This is the reset default (HSI at 64 MHz
/// feeding `ck_ker_usart6`); if the clock tree reparents USART6 before the CM33
/// comes up, the divider is wrong and every byte arrives as a framing error. At
/// 64 MHz the 921 600 baud divider rounds to 69, i.e. ~927.5 kbaud — 0.6 % fast,
/// comfortably inside the ±2 % an 8N1 receiver tolerates.
const USART6_KERNEL_CLOCK_HZ: u32 = 64_000_000;

/// IWR6843 data-UART baud rate. Must match the `.cfg` flashed on the sensor;
/// TI's out-of-box and Radar Toolbox demos both default to this.
const RADAR_BAUD: u32 = 921_600;

/// Receive ring behind [`BufferedUart`]. At 921 600 baud the UART delivers
/// ~92 KiB/s, so 8 KiB absorbs ~90 ms of stream — more than one frame period,
/// which is what keeps a scheduling hiccup from cutting a packet in half.
const RX_RING_LEN: usize = 8 * 1024;

/// Largest packet [`PacketAssembler`] will accept. An Out-of-Box frame with 96
/// points and side info is under 2 KiB; 4 KiB leaves room for extra TLVs.
const MAX_PACKET_LEN: usize = 4 * 1024;

/// Working buffer for one UART read.
const READ_CHUNK: usize = 512;

/// How long to keep reading for a frame before answering the CA35 with a stale
/// report. Keeps the pull loop responsive when the sensor is quiet or unpowered
/// instead of stalling until it speaks again.
const READ_TIMEOUT: Duration = Duration::from_millis(50);

static USART6_STATE: BufferedUartState = BufferedUartState::new();
static mut USART6_RX_RING: [u8; RX_RING_LEN] = [0; RX_RING_LEN];

#[consortium_runtime_mcu::main]
async fn main(context: Context, _spawner: Spawner) {
    let mut radar = context.ipc_shm.radar;

    // Route USART6's vector before the driver enables its receive interrupt.
    // SAFETY: the interrupt number is USART6's from the validated chip map, the
    // handler below is installed on `USART6_STATE`, and this runs once during
    // bring-up before any other code masks interrupts.
    unsafe {
        consortium_hal_stm32mp2::hal::nvic::set_priority(Interrupt::USART6 as u16, 0x80);
        consortium_hal_stm32mp2::hal::nvic::enable(Interrupt::USART6 as u16);
    }

    // SAFETY: the ring is taken exactly once, here, and handed to the single
    // `BufferedUart` that owns it for the rest of the program; nothing else
    // names `USART6_RX_RING`.
    let rx_ring: &'static mut [u8] = unsafe { &mut *core::ptr::addr_of_mut!(USART6_RX_RING) };

    // SAFETY: `USART6_BASE` is USART6's validated non-secure base from the chip
    // map, owned exclusively by this driver; `USART6_STATE` and `rx_ring` are
    // dedicated to this instance, and its interrupt is routed to that state
    // above. The pins are already muxed to USART6 for this core.
    let uart = unsafe {
        BufferedUart::new(
            USART6_BASE,
            USART6_KERNEL_CLOCK_HZ,
            Config {
                baudrate: RADAR_BAUD,
            },
            &USART6_STATE,
            rx_ring,
        )
    };
    // The radar only talks; nothing is ever written back on this port.
    let (_tx, mut rx) = uart.split();

    defmt::info!("radar front-end up: USART6 @ {=u32} baud", RADAR_BAUD);

    let mut assembler = PacketAssembler::<MAX_PACKET_LEN>::new();
    let mut read_buffer = [0u8; READ_CHUNK];
    let mut seq: u32 = 0;
    // Frames parsed but not yet delivered, and frames overwritten before the
    // CA35 collected them. Both reset once reported.
    let mut latest: Option<RadarReport> = None;
    let mut dropped: u16 = 0;
    let mut overrun = false;

    loop {
        // Pull: one CA35 request, one report back.
        let streaming = match radar.recv().await {
            Ok(message) => {
                let control: RadarControl = message.into_inner();
                control.streaming
            }
            Err(_) => {
                defmt::error!("radar ipc recv error; front-end stopping");
                break;
            }
        };

        if streaming && latest.is_none() {
            // Read until a frame completes or the deadline passes. Bytes that
            // arrive meanwhile keep accumulating in the ring, so a timeout costs
            // latency, never data.
            let _ = with_timeout(READ_TIMEOUT, async {
                loop {
                    let received = match rx.read(&mut read_buffer).await {
                        Ok(received) => received,
                        Err(_) => {
                            // A line error already dropped bytes; the partial
                            // packet in the assembler is untrustworthy.
                            defmt::warn!("usart6 line error");
                            overrun = true;
                            assembler.reset();
                            return;
                        }
                    };

                    let mut completed = false;
                    assembler.push(&read_buffer[..received], |packet| {
                        match parse_report(packet) {
                            Ok(report) => {
                                if latest.is_some() {
                                    dropped = dropped.saturating_add(1);
                                }
                                latest = Some(report);
                                completed = true;
                            }
                            // A packet that framed but would not parse is a
                            // frame lost as surely as one never received.
                            Err(_) => dropped = dropped.saturating_add(1),
                        }
                    });
                    if completed {
                        return;
                    }
                }
            })
            .await;
        }

        // The IRQ handler latches ring overflows; either way the stream has a
        // hole, so whatever is half-assembled has to go.
        if USART6_STATE.take_overrun() {
            overrun = true;
            assembler.reset();
        }
        if overrun {
            defmt::warn!("usart6 rx overrun at seq={=u32}", seq);
        }

        let mut report = latest.take().unwrap_or_else(|| RadarReport::empty(seq));
        report.seq = seq;
        report.dropped = dropped;
        report.overrun = overrun;
        dropped = 0;
        overrun = false;

        if radar.send(&report).await.is_err() {
            defmt::error!("radar ipc send error; front-end stopping");
            break;
        }
        seq = seq.wrapping_add(1);
    }
}

// IPCC RX-occupied vectors: the application owns these and forwards each to the
// shared IPCC waker so waiting `IpccDoorbell::wait` futures make progress.
#[interrupt]
fn IPCC1_RX() {
    consortium_runtime_mcu::log::trace!("ipcc1_rx interrupt: doorbell RX occupied");
    // SAFETY: this is the validated IPCC1 base used by the generated
    // Secondary-side doorbell.
    unsafe {
        consortium_ipc_doorbell_ipcc::notify_rx_occupied_interrupt::<consortium_ipc::Secondary, 1>(
            0x4049_0000,
        );
    }
}

// Drains the USART6 receive FIFO into the ring and wakes the pending read.
#[interrupt]
fn USART6() {
    USART6_STATE.on_interrupt();
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    cortex_m::interrupt::disable();
    loop {
        core::sync::atomic::compiler_fence(core::sync::atomic::Ordering::SeqCst);
        cortex_m::asm::wfi();
    }
}
