// SPDX-License-Identifier: Apache-2.0

//! 404-snf CM33 firmware: the pneumatic safety supervisor.
//!
//! The pump and pressure sensor run on the CA35 (no PWM-capable timer the CM33
//! could reach is free on the DK). The CM33's job is the one thing you don't
//! trust a Linux userspace loop with: an independent, always-running interlock.
//!
//! It holds a **deadman** on the CA35 heartbeat delivered over the generated
//! `actuator` transceiver: each [`PneumaticCommand`] refreshes the timer and, if
//! `pump_enable` is set, energizes the pump power rail through one GPIO
//! (load-switch on the motor rail — see `hardware/pneumatics/README.md`). If no
//! heartbeat arrives within [`HEARTBEAT_TIMEOUT`] — Linux hung, panicked, or the
//! IPC stalled — it cuts the rail (fail-safe) and reports the trip in
//! [`PneumaticStatus`]. The rail starts de-energized and is only enabled once a
//! live heartbeat asks for it.
//!
//! All shared-memory / doorbell / MPU / NVIC / time-driver / peripheral bring-up
//! lives in `consortium.gen.rs`, generated by `csti build` from
//! `../../Consortium.toml` and `include!`d below. `#[consortium_runtime_mcu::main]`
//! calls the generated `init()` and hands the body a `Context` whose
//! `ipc_shm.actuator` field is a `Transceiver<PneumaticStatus, PneumaticCommand>`
//! and whose `peripherals.gpioh` field is the interlock GPIO port.

#![no_std]
#![no_main]

use consortium_hal_stm32mp2::gpio::Level;
use consortium_hal_stm32mp2::interrupt;
use embassy_executor::Spawner;
use embassy_time::{Duration, with_timeout};
use snf_shared::{PneumaticCommand, PneumaticStatus};

// Generated by `csti build`; absent until the pipeline runs (see this crate's
// README). Depending on `consortium-dbg` with `logger` registers the defmt sink.
include!("consortium.gen.rs");

/// Longest gap between CA35 heartbeats before the deadman trips and cuts the
/// pump rail. Comfortably above the CA35's ~100 ms heartbeat period.
const HEARTBEAT_TIMEOUT: Duration = Duration::from_millis(500);

/// GPIOH pin driving the pump-rail load-switch. Placeholder pending board
/// design; `Consortium.toml` grants the CM33 the whole `gpioh` port.
const RAIL_PIN: u8 = 6;

#[consortium_runtime_mcu::main]
async fn main(context: Context, _spawner: Spawner) {
    let mut actuator = context.ipc_shm.actuator;

    // Interlock output starts de-energized: the pump rail stays cut until a live
    // heartbeat explicitly asks to enable it.
    let mut rail = context
        .peripherals
        .gpioh
        .pin(RAIL_PIN)
        .into_output(Level::Low);

    let mut seq: u32 = 0;
    let mut rail_enabled = false;
    let mut tripped = false;

    loop {
        match with_timeout(HEARTBEAT_TIMEOUT, actuator.recv()).await {
            // Fresh heartbeat: clear any trip and follow the CA35's enable request.
            Ok(Ok(msg)) => {
                let cmd: PneumaticCommand = msg.into_inner();
                tripped = false;
                rail_enabled = cmd.pump_enable;
                if rail_enabled {
                    rail.set_high();
                } else {
                    rail.set_low();
                }
                defmt::trace!(
                    "heartbeat seq={=u32} pump_enable={=bool}",
                    cmd.seq,
                    cmd.pump_enable,
                );
            }
            // IPC error: fail safe and stop — the channel is unusable.
            Ok(Err(_)) => {
                rail.set_low();
                defmt::error!("actuator ipc error; pump rail cut");
                break;
            }
            // Deadman: no heartbeat in time. Cut the rail and latch the trip.
            Err(_) => {
                rail.set_low();
                rail_enabled = false;
                if !tripped {
                    tripped = true;
                    defmt::warn!("deadman tripped: CA35 heartbeat lost; pump rail cut");
                }
            }
        }

        let status = PneumaticStatus {
            rail_enabled,
            tripped,
            seq,
        };
        let _ = actuator.send(&status).await;
        seq = seq.wrapping_add(1);
    }
}

// IPCC RX-occupied vectors: the application owns these and forwards each to the
// shared IPCC waker so waiting `IpccDoorbell::wait` futures make progress.
#[interrupt]
fn IPCC1_RX() {
    consortium_runtime_mcu::log::trace!("ipcc1_rx interrupt: doorbell RX occupied");
    // SAFETY: this is the validated IPCC1 base used by the generated
    // Secondary-side doorbell.
    unsafe {
        consortium_ipc_doorbell_ipcc::notify_rx_occupied_interrupt::<consortium_ipc::Secondary, 1>(
            0x4049_0000,
        );
    }
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    cortex_m::interrupt::disable();
    loop {
        core::sync::atomic::compiler_fence(core::sync::atomic::Ordering::SeqCst);
        cortex_m::asm::wfi();
    }
}
